export default {
avatar_url: "https://avatars.githubusercontent.com/u/1500684?v=4",
bio: "Improving the world w/ quality software · Husband, Father, Latter-day Saint, Teacher, OSS · http://TestingJavaScript.com · http://EpicReact.Dev · Be Kind",
blog: "https://kentcdodds.com",
company: "@kentcdodds",
created_at: "2012-03-04T22:32:01Z",
email: null,
events_url: "https://api.github.com/users/kentcdodds/events{/privacy}",
followers: 18516,
followers_url: "https://api.github.com/users/kentcdodds/followers",
following: 42,
following_url: "https://api.github.com/users/kentcdodds/following{/other_user}",
gists_url: "https://api.github.com/users/kentcdodds/gists{/gist_id}",
gravatar_id: "",
hireable: null,
html_url: "https://github.com/kentcdodds",
id: 1500684,
location: "Salt Lake City, Utah, USA",
login: "kentcdodds",
name: "Kent C. Dodds",
node_id: "MDQ6VXNlcjE1MDA2ODQ=",
organizations_url: "https://api.github.com/users/kentcdodds/orgs",
public_gists: 213,
public_repos: 611,
received_events_url: "https://api.github.com/users/kentcdodds/received_events",
repos_url: "https://api.github.com/users/kentcdodds/repos",
site_admin: false,
starred_url: "https://api.github.com/users/kentcdodds/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/kentcdodds/subscriptions",
twitter_username: "kentcdodds",
type: "User",
updated_at: "2021-04-01T06:36:36Z",
url: "https://api.github.com/users/kentcdodds"
};